# Title of the page
title: "ACM Research: Object Detection Modelling with Thermal Imaging"
# Your name
author: Abhishek A. Mishra
# Show a link to LinkedIn in the header intro. Comment out to disable.
#linkedin: https://www.linkedin.com/in/guptaneil/
# Show a link at the top of your timeline to your main personal site
# Comment this out to disable
#personal_site:
  #url: https://acm-objdetect.gg
  #title: acm-objdetect.gg
# show today marker at end of timeline
show_today: true

# Your timeline is split into periods (e.g., decades, childhood/teens/adult, "Before Timeliner"/"After Timeliner", etc)
# Each period has a list of events formatted as `- date: title`. If you don't want to have period dividers, leave out the name field.
periods:
  - name: Week One
    events:
    - Task One : "Introducing ourselves (and me!) and our mentor!"
    - Task Two : "Introduction to project and Keras and TensorFlow"
    - Task Three : "Intro to Image Detection in Tensorflow and Keras"
    - Homework : "Run a readymade image detection folder for image classification with Tensorflow/Keras and understand every each aspect"
  - name: Week Two
    events:
    - Task One : "Assigning research papers"
    - Task Two : "How to tackle complex image detection"
    - Task Three : "Introduction to transfer learning"
    - Homework : "Next meeting, come back with notes and summarized versions of what you learnt."
  - name: Week Three
    events:
    - Task One : "Introducing dataset"
    - Task Two : "Access to dataset and nature of dataset"
    - Task Three : "Introduction to COCO image processing and how to preprocesss COCO"
    - What is COCO Dataset : >-
        <a href="https://blog.roboflow.com/coco-dataset/" target="_blank" rel="noopener" title="COCO Dataset"></a>.
    - What is COCO : <a href="https://datagen.tech/guides/image-datasets/ms-coco-dataset-using-it-in-your-computer-vision-projects/" target="_blank" rel="noopener" title="What is COCO"></a>.
    #- What are COCO Detection Metrics : [Detection Evaluation](https://cocodataset.org/#detection-eval)
    #- Annotation Converters : [Github Link](https://github.com/nikhilgunti/Annotation-Converters)
    - Homework : "By next meeting, understand COCO annotations and practice preprocessing COCO format"
  - name: Week Four
    events:
    - Task One : "Introduction to ResNet and co."
      #- What is Transfer Learning : [Transfer Learning Introduction](https://www.v7labs.com/blog/transfer-learning-guide)
      #- YOLOv7 : [Introduction and Demo of YOLOv7](https://viso.ai/deep-learning/yolov7-guide/)
      #  - Demo : [Demo](https://huggingface.co/spaces/akhaliq/yolov7)
      #- How to use YOLOV7 : [Usage of YOLOv7](https://inside-machinelearning.com/en/use-yolov7/)
      #  - Official Github Repo for YOLOv7 : [Github Link](https://github.com/wongkinyiu/yolov7)
      #- Keras Pretrained Models : [Multiple Models Available](https://keras.io/api/applications/)
    - Task Two : "Continue working on COCO format to understand preprocessing"
    - Homework : "Finish COCO preprocessing and start modelling"
  - name: Week Five
    events:
    - Task One : Continue work on COCO preprocessing 
    - Task Two : "Work on modelling and producing evaluations from model and comparing them to other models"
    - Task Three : "Introduction to OpenCV to showcase model and results"
    #  - Webcam Usage : [Online Documentation](https://opencv.org/)
    #  - Sample Code Template : [Github Link](https://github.com/abhiamishra/computer-vision-practice/blob/main/handtrack/handtrack.py)
    - Homework : "Continue working on COCO preprocessing, start on modelling + OpenCV"
  - name: Week Six
    events:
    - Task One : "Finish modelling and start work on poster"
    - Homework : "Work on the web app and poster"
  - name: Week Seven
    events:
    - Task One : "Continue working on poster and app"
    - Homework : "Work on the web app and poster"
  - name: Week Eight
    events:
    - Task One : "Finalize poster and start presentation"
    - Homework : "Work on the web app and presentation"
  - name: Week Nine
    events:
    - Task One : "Work on presentation, slides, and finish web app"
    - Homework : "Prepare presenting and finish the web app"
  - name: Week Ten
    events:
    - Task One : "Finalize the presentation"
    - Finish Line : Congrats, you are finished!
