# Title of the page
title: "ACM Research: Object Detection Modelling with Thermal Imaging"
# Your name
author: Abhishek A. Mishra
# Show a link to LinkedIn in the header intro. Comment out to disable.
#linkedin: https://www.linkedin.com/in/guptaneil/
# Show a link at the top of your timeline to your main personal site
# Comment this out to disable
#personal_site:
  #url: https://neil.gg
  #title: neil.gg
# show today marker at end of timeline
show_today: true

# Your timeline is split into periods (e.g., decades, childhood/teens/adult, "Before Timeliner"/"After Timeliner", etc)
# Each period has a list of events formatted as `- date: title`. If you don't want to have period dividers, leave out the name field.
periods:
  - name: Week One
    events:
    - Task One : "Introducing ourselves (and me!) "
    - Task Two : "Introduction to project and TensorFlow"
    - Task Three : "Intro to Image Detection in Tensorflow and Keras"
    - Homework : "Run a readymade image detection folder for image classification with Tensorflow/Keras and understand every each aspect"
  - name: Week Two
    events:
    - Task One : "Assigning research papers"
    - Task Two : "How to tackle complex image detection"
    - Homework : "Next meeting, come back with notes and summarized versions of what you learnt."
  - name: Week Three
    events:
    - Task One : "Introducing dataset"
    - Task Two : "Access to dataset and nature of dataset"
    - Task Three : "Introduction to COCO image processing and how to preprocesss COCO"
    - Homework : "By next meeting, understand COCO annotations and practice preprocessing COCO format"
  - name: Week Four
    events:
    - Task One : "Introduction to ResNet and co."
    - Task Two : "Continue working on COCO format to understand preprocessing"
    - Homework : "Finish COCO preprocessing and start modelling"
  - name: Week Five
    events:
    - Task One : "Work on modelling and producing evaluations from model and comparing them to other models"
    - Task Two : "Make a *small and simple* web app to showcase model and results"
    - Homework : "Work on modelling + web app"
  - name: Week Six
    events:
    - Task One : "Finish modelling and start work on poster"
    - Homework : "Work on the web app and poster"
  - name: Week Seven
    events:
    - Task One : "Continue working on poster and app"
    - Homework : "Work on the web app and poster"
  - name: Week Eight
    events:
    - Task One : "Finalize poster and start presentation"
    - Homework : "Work on the web app and presentation"
  - name: Week Nine
    events:
    - Task One : "Work on presentation, slides, and finish web app"
    - Homework : "Prepare presenting and finish the web app"
  - name: Week Ten
    events:
    - Task One : "Finalize the presentation"
    - Finish Line : Congrats, you are finished!